// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.User.Assignable.MultiProjectSearch;
using Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.User.Assignable.Search;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.User.Assignable
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\2\user\assignable
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssignableRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The multiProjectSearch property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.User.Assignable.MultiProjectSearch.MultiProjectSearchRequestBuilder MultiProjectSearch
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.User.Assignable.MultiProjectSearch.MultiProjectSearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.User.Assignable.Search.SearchRequestBuilder Search
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.User.Assignable.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.User.Assignable.AssignableRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssignableRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/2/user/assignable", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.User.Assignable.AssignableRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssignableRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/2/user/assignable", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
