// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children
{
    /// <summary>
    /// Builds and executes requests for operations under \pages\{-id}\children
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChildrenRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChildrenRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pages/{%2Did}/children{?cursor*,limit*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChildrenRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pages/{%2Did}/children{?cursor*,limit*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns all child pages for given page id. The number of results is limited by the `limit` parameter and additional results (if available)will be available through the `next` URL present in the `Link` response header.**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:Permission to access the Confluence site (&apos;Can use&apos; global permission).Only pages that the user has permission to view will be returned.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenGetResponse?> GetAsChildrenGetResponseAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenGetResponse> GetAsChildrenGetResponseAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenGetResponse>(requestInfo, global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns all child pages for given page id. The number of results is limited by the `limit` parameter and additional results (if available)will be available through the `next` URL present in the `Link` response header.**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:Permission to access the Confluence site (&apos;Can use&apos; global permission).Only pages that the user has permission to view will be returned.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsChildrenGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenResponse?> GetAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenResponse> GetAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenResponse>(requestInfo, global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns all child pages for given page id. The number of results is limited by the `limit` parameter and additional results (if available)will be available through the `next` URL present in the `Link` response header.**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:Permission to access the Confluence site (&apos;Can use&apos; global permission).Only pages that the user has permission to view will be returned.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        [Obsolete("")]
        public global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns all child pages for given page id. The number of results is limited by the `limit` parameter and additional results (if available)will be available through the `next` URL present in the `Link` response header.**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:Permission to access the Confluence site (&apos;Can use&apos; global permission).Only pages that the user has permission to view will be returned.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChildrenRequestBuilderGetQueryParameters 
        {
            /// <summary>Used for pagination, this opaque cursor will be returned in the `next` URL in the `Link` response header. Use the relative URL in the `Link` header to retrieve the `next` set of results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>Maximum number of pages per result to return. If more results exist, use the `Link` header to retrieve a relative URL that will return the next set of results.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Used to sort the result by a particular field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChildrenRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.Pages.Item.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
