// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>
    /// Bulk Transition Get Available Transitions Response.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BulkTransitionGetAvailableTransitions : IParsable
    {
        /// <summary>List of available transitions for bulk transition operation for requested issues grouped by workflow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueBulkTransitionForWorkflow>? AvailableTransitions { get; private set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueBulkTransitionForWorkflow> AvailableTransitions { get; private set; }
#endif
        /// <summary>The end cursor for use in pagination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndingBefore { get; private set; }
#nullable restore
#else
        public string EndingBefore { get; private set; }
#endif
        /// <summary>The start cursor for use in pagination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartingAfter { get; private set; }
#nullable restore
#else
        public string StartingAfter { get; private set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.BulkTransitionGetAvailableTransitions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.Models.BulkTransitionGetAvailableTransitions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.Models.BulkTransitionGetAvailableTransitions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "availableTransitions", n => { AvailableTransitions = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueBulkTransitionForWorkflow>(global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueBulkTransitionForWorkflow.CreateFromDiscriminatorValue)?.AsList(); } },
                { "endingBefore", n => { EndingBefore = n.GetStringValue(); } },
                { "startingAfter", n => { StartingAfter = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        }
    }
}
#pragma warning restore CS0618
