// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>The permission holder type. This must be &quot;Group&quot; or &quot;AccountId&quot;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreatePermissionHolderRequest_type
    {
        [EnumMember(Value = "Group")]
        #pragma warning disable CS1591
        Group,
        #pragma warning restore CS1591
        [EnumMember(Value = "AccountId")]
        #pragma warning disable CS1591
        AccountId,
        #pragma warning restore CS1591
    }
}
