// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateSchedulingRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The dependencies for the plan. This must be &quot;Sequential&quot; or &quot;Concurrent&quot;.</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest_dependencies? Dependencies { get; set; }
        /// <summary>The end date field for the plan.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateDateFieldRequest? EndDate { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateDateFieldRequest EndDate { get; set; }
#endif
        /// <summary>The estimation unit for the plan. This must be &quot;StoryPoints&quot;, &quot;Days&quot; or &quot;Hours&quot;.</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest_estimation? Estimation { get; set; }
        /// <summary>The inferred dates for the plan. This must be &quot;None&quot;, &quot;SprintDates&quot; or &quot;ReleaseDates&quot;.</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest_inferredDates? InferredDates { get; set; }
        /// <summary>The start date field for the plan.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateDateFieldRequest? StartDate { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateDateFieldRequest StartDate { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dependencies", n => { Dependencies = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest_dependencies>(); } },
                { "endDate", n => { EndDate = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateDateFieldRequest>(global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateDateFieldRequest.CreateFromDiscriminatorValue); } },
                { "estimation", n => { Estimation = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest_estimation>(); } },
                { "inferredDates", n => { InferredDates = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest_inferredDates>(); } },
                { "startDate", n => { StartDate = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateDateFieldRequest>(global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateDateFieldRequest.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest_dependencies>("dependencies", Dependencies);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateDateFieldRequest>("endDate", EndDate);
            writer.WriteEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest_estimation>("estimation", Estimation);
            writer.WriteEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateSchedulingRequest_inferredDates>("inferredDates", InferredDates);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.CreateDateFieldRequest>("startDate", StartDate);
        }
    }
}
#pragma warning restore CS0618
