// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>The operator between the field and operand.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FieldValueClause_operator
    {
        [EnumMember(Value = "=")]
        #pragma warning disable CS1591
        Equal,
        #pragma warning restore CS1591
        [EnumMember(Value = "!=")]
        #pragma warning disable CS1591
        ExclamationEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = ">")]
        #pragma warning disable CS1591
        GreaterThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "<")]
        #pragma warning disable CS1591
        LessThan,
        #pragma warning restore CS1591
        [EnumMember(Value = ">=")]
        #pragma warning disable CS1591
        GreaterThanEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "<=")]
        #pragma warning disable CS1591
        LessThanEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "in")]
        #pragma warning disable CS1591
        In,
        #pragma warning restore CS1591
        [EnumMember(Value = "not in")]
        #pragma warning disable CS1591
        NotIn,
        #pragma warning restore CS1591
        [EnumMember(Value = "~")]
        #pragma warning disable CS1591
        Tilde,
        #pragma warning restore CS1591
        [EnumMember(Value = "~=")]
        #pragma warning disable CS1591
        TildeEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "is")]
        #pragma warning disable CS1591
        Is,
        #pragma warning restore CS1591
        [EnumMember(Value = "is not")]
        #pragma warning disable CS1591
        IsNot,
        #pragma warning restore CS1591
    }
}
