// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>
    /// Details of an issue update request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IssueUpdateDetails : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of issue screen fields to update, specifying the sub-field to update and its value for each field. This field provides a straightforward option when setting a sub-field. When multiple sub-fields or other operations are required, use `update`. Fields included in here cannot be included in `update`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails_fields? Fields { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails_fields Fields { get; set; }
#endif
        /// <summary>Additional issue history details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.HistoryMetadata? HistoryMetadata { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.HistoryMetadata HistoryMetadata { get; set; }
#endif
        /// <summary>Details of issue properties to be add or update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.EntityProperty>? Properties { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.EntityProperty> Properties { get; set; }
#endif
        /// <summary>Details of a transition. Required when performing a transition, optional when creating or editing an issue.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTransition? Transition { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTransition Transition { get; set; }
#endif
        /// <summary>A Map containing the field field name and a list of operations to perform on the issue screen field. Note that fields included in here cannot be included in `fields`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails_update? Update { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails_update Update { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails"/> and sets the default values.
        /// </summary>
        public IssueUpdateDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "fields", n => { Fields = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails_fields>(global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails_fields.CreateFromDiscriminatorValue); } },
                { "historyMetadata", n => { HistoryMetadata = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.HistoryMetadata>(global::Kubis1982.Atlassian.Jira.RestClient.Models.HistoryMetadata.CreateFromDiscriminatorValue); } },
                { "properties", n => { Properties = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.EntityProperty>(global::Kubis1982.Atlassian.Jira.RestClient.Models.EntityProperty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "transition", n => { Transition = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTransition>(global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTransition.CreateFromDiscriminatorValue); } },
                { "update", n => { Update = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails_update>(global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails_update.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails_fields>("fields", Fields);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.HistoryMetadata>("historyMetadata", HistoryMetadata);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.EntityProperty>("properties", Properties);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTransition>("transition", Transition);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueUpdateDetails_update>("update", Update);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
