// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>The conflict strategy to use when the issue type already exists. FAIL - Fail execution, this always needs to be unique; USE - Use the existing entity and ignore new entity parameters</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IssueTypePayload_onConflict
    {
        [EnumMember(Value = "FAIL")]
        #pragma warning disable CS1591
        FAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "USE")]
        #pragma warning disable CS1591
        USE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEW")]
        #pragma warning disable CS1591
        NEW,
        #pragma warning restore CS1591
    }
}
