// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>The category of the status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum JiraWorkflowStatus_statusCategory
    {
        [EnumMember(Value = "TODO")]
        #pragma warning disable CS1591
        TODO,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_PROGRESS")]
        #pragma warning disable CS1591
        IN_PROGRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "DONE")]
        #pragma warning disable CS1591
        DONE,
        #pragma warning restore CS1591
    }
}
