// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>
    /// Details about a project.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Project : IParsable
    {
        /// <summary>Whether the project is archived.</summary>
        public bool? Archived { get; private set; }
        /// <summary>The user who archived the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.User? ArchivedBy { get; private set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.User ArchivedBy { get; private set; }
#endif
        /// <summary>The date when the project was archived.</summary>
        public DateTimeOffset? ArchivedDate { get; private set; }
        /// <summary>The default assignee when creating issues for this project.</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_assigneeType? AssigneeType { get; private set; }
        /// <summary>The URLs of the project&apos;s avatars.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.AvatarUrlsBean? AvatarUrls { get; private set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.AvatarUrlsBean AvatarUrls { get; private set; }
#endif
        /// <summary>List of the components contained in the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectComponent>? Components { get; private set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectComponent> Components { get; private set; }
#endif
        /// <summary>Whether the project is marked as deleted.</summary>
        public bool? Deleted { get; private set; }
        /// <summary>The user who marked the project as deleted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.User? DeletedBy { get; private set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.User DeletedBy { get; private set; }
#endif
        /// <summary>The date when the project was marked as deleted.</summary>
        public DateTimeOffset? DeletedDate { get; private set; }
        /// <summary>A brief description of the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; private set; }
#nullable restore
#else
        public string Description { get; private set; }
#endif
        /// <summary>An email address associated with the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Expand options that include additional project details in the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Expand { get; private set; }
#nullable restore
#else
        public string Expand { get; private set; }
#endif
        /// <summary>Whether the project is selected as a favorite.</summary>
        public bool? Favourite { get; set; }
        /// <summary>The ID of the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Insights about the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectInsight? Insight { get; private set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectInsight Insight { get; private set; }
#endif
        /// <summary>Whether the project is private from the user&apos;s perspective. This means the user can&apos;t see the project or any associated issues.</summary>
        public bool? IsPrivate { get; private set; }
        /// <summary>The issue type hierarchy for the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.Hierarchy? IssueTypeHierarchy { get; private set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.Hierarchy IssueTypeHierarchy { get; private set; }
#endif
        /// <summary>List of the issue types available in the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTypeDetails>? IssueTypes { get; private set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTypeDetails> IssueTypes { get; private set; }
#endif
        /// <summary>The key of the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; private set; }
#nullable restore
#else
        public string Key { get; private set; }
#endif
        /// <summary>The project landing page info.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectLandingPageInfo? LandingPageInfo { get; private set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectLandingPageInfo LandingPageInfo { get; private set; }
#endif
        /// <summary>The username of the project lead.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.User? Lead { get; private set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.User Lead { get; private set; }
#endif
        /// <summary>The name of the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; private set; }
#nullable restore
#else
        public string Name { get; private set; }
#endif
        /// <summary>User permissions on the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectPermissions? Permissions { get; private set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectPermissions Permissions { get; private set; }
#endif
        /// <summary>The category the project belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectCategory? ProjectCategory { get; private set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectCategory ProjectCategory { get; private set; }
#endif
        /// <summary>The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project.</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_projectTypeKey? ProjectTypeKey { get; private set; }
        /// <summary>Map of project properties</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_properties? Properties { get; private set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_properties Properties { get; private set; }
#endif
        /// <summary>The date when the project is deleted permanently.</summary>
        public DateTimeOffset? RetentionTillDate { get; private set; }
        /// <summary>The name and self URL for each role defined in the project. For more information, see [Create project role](#api-rest-api-3-role-post).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_roles? Roles { get; private set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_roles Roles { get; private set; }
#endif
        /// <summary>The URL of the project details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Self { get; private set; }
#nullable restore
#else
        public string Self { get; private set; }
#endif
        /// <summary>Whether the project is simplified.</summary>
        public bool? Simplified { get; private set; }
        /// <summary>The type of the project.</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_style? Style { get; private set; }
        /// <summary>A link to information about this project, such as project documentation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; private set; }
#nullable restore
#else
        public string Url { get; private set; }
#endif
        /// <summary>Unique ID for next-gen projects.</summary>
        public Guid? Uuid { get; private set; }
        /// <summary>The versions defined in the project. For more information, see [Create version](#api-rest-api-3-version-post).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.VersionObject>? Versions { get; private set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.VersionObject> Versions { get; private set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.Project"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.Models.Project CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.Models.Project();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "archivedBy", n => { ArchivedBy = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.User>(global::Kubis1982.Atlassian.Jira.RestClient.Models.User.CreateFromDiscriminatorValue); } },
                { "archivedDate", n => { ArchivedDate = n.GetDateTimeOffsetValue(); } },
                { "assigneeType", n => { AssigneeType = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_assigneeType>(); } },
                { "avatarUrls", n => { AvatarUrls = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.AvatarUrlsBean>(global::Kubis1982.Atlassian.Jira.RestClient.Models.AvatarUrlsBean.CreateFromDiscriminatorValue); } },
                { "components", n => { Components = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectComponent>(global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectComponent.CreateFromDiscriminatorValue)?.AsList(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "deletedBy", n => { DeletedBy = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.User>(global::Kubis1982.Atlassian.Jira.RestClient.Models.User.CreateFromDiscriminatorValue); } },
                { "deletedDate", n => { DeletedDate = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "expand", n => { Expand = n.GetStringValue(); } },
                { "favourite", n => { Favourite = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "insight", n => { Insight = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectInsight>(global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectInsight.CreateFromDiscriminatorValue); } },
                { "isPrivate", n => { IsPrivate = n.GetBoolValue(); } },
                { "issueTypeHierarchy", n => { IssueTypeHierarchy = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.Hierarchy>(global::Kubis1982.Atlassian.Jira.RestClient.Models.Hierarchy.CreateFromDiscriminatorValue); } },
                { "issueTypes", n => { IssueTypes = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTypeDetails>(global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTypeDetails.CreateFromDiscriminatorValue)?.AsList(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "landingPageInfo", n => { LandingPageInfo = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectLandingPageInfo>(global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectLandingPageInfo.CreateFromDiscriminatorValue); } },
                { "lead", n => { Lead = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.User>(global::Kubis1982.Atlassian.Jira.RestClient.Models.User.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "permissions", n => { Permissions = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectPermissions>(global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectPermissions.CreateFromDiscriminatorValue); } },
                { "projectCategory", n => { ProjectCategory = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectCategory>(global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectCategory.CreateFromDiscriminatorValue); } },
                { "projectTypeKey", n => { ProjectTypeKey = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_projectTypeKey>(); } },
                { "properties", n => { Properties = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_properties>(global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_properties.CreateFromDiscriminatorValue); } },
                { "retentionTillDate", n => { RetentionTillDate = n.GetDateTimeOffsetValue(); } },
                { "roles", n => { Roles = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_roles>(global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_roles.CreateFromDiscriminatorValue); } },
                { "self", n => { Self = n.GetStringValue(); } },
                { "simplified", n => { Simplified = n.GetBoolValue(); } },
                { "style", n => { Style = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.Project_style>(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "uuid", n => { Uuid = n.GetGuidValue(); } },
                { "versions", n => { Versions = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.VersionObject>(global::Kubis1982.Atlassian.Jira.RestClient.Models.VersionObject.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("email", Email);
            writer.WriteBoolValue("favourite", Favourite);
            writer.WriteStringValue("id", Id);
        }
    }
}
#pragma warning restore CS0618
