// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>
    /// Details of an issue type hierarchy level.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectIssueTypesHierarchyLevel : IParsable
    {
        /// <summary>The ID of the issue type hierarchy level. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/).</summary>
        public Guid? EntityId { get; private set; }
        /// <summary>The list of issue types in the hierarchy level.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTypeInfo>? IssueTypes { get; private set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTypeInfo> IssueTypes { get; private set; }
#endif
        /// <summary>The level of the issue type hierarchy level.</summary>
        public int? Level { get; private set; }
        /// <summary>The name of the issue type hierarchy level.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; private set; }
#nullable restore
#else
        public string Name { get; private set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectIssueTypesHierarchyLevel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectIssueTypesHierarchyLevel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectIssueTypesHierarchyLevel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entityId", n => { EntityId = n.GetGuidValue(); } },
                { "issueTypes", n => { IssueTypes = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTypeInfo>(global::Kubis1982.Atlassian.Jira.RestClient.Models.IssueTypeInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "level", n => { Level = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        }
    }
}
#pragma warning restore CS0618
