// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>
    /// The issue types using this status in a project.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusProjectIssueTypeUsageDTO : IParsable
    {
        /// <summary>A page of issue types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusProjectIssueTypeUsagePage? IssueTypes { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusProjectIssueTypeUsagePage IssueTypes { get; set; }
#endif
        /// <summary>The project ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>The status ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusId { get; set; }
#nullable restore
#else
        public string StatusId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusProjectIssueTypeUsageDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusProjectIssueTypeUsageDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusProjectIssueTypeUsageDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "issueTypes", n => { IssueTypes = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusProjectIssueTypeUsagePage>(global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusProjectIssueTypeUsagePage.CreateFromDiscriminatorValue); } },
                { "projectId", n => { ProjectId = n.GetStringValue(); } },
                { "statusId", n => { StatusId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusProjectIssueTypeUsagePage>("issueTypes", IssueTypes);
            writer.WriteStringValue("projectId", ProjectId);
            writer.WriteStringValue("statusId", StatusId);
        }
    }
}
#pragma warning restore CS0618
