// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>
    /// The details of the workflows to update.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowUpdate : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The mapping of old to new status ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusMigration>? DefaultStatusMappings { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusMigration> DefaultStatusMappings { get; set; }
#endif
        /// <summary>The new description for this workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The ID of this workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The starting point for the statuses in the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowLayout? LoopedTransitionContainerLayout { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowLayout LoopedTransitionContainerLayout { get; set; }
#endif
        /// <summary>The starting point for the statuses in the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowLayout? StartPointLayout { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowLayout StartPointLayout { get; set; }
#endif
        /// <summary>The statuses associated with this workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusLayoutUpdate>? Statuses { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusLayoutUpdate> Statuses { get; set; }
#endif
        /// <summary>The mapping of old to new status ID for a specific project and issue type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusMappingDTO>? StatusMappings { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusMappingDTO> StatusMappings { get; set; }
#endif
        /// <summary>The transitions of this workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.TransitionUpdateDTO>? Transitions { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.TransitionUpdateDTO> Transitions { get; set; }
#endif
        /// <summary>The current version details of this workflow scheme.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.DocumentVersion? Version { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.DocumentVersion Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowUpdate"/> and sets the default values.
        /// </summary>
        public WorkflowUpdate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "defaultStatusMappings", n => { DefaultStatusMappings = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusMigration>(global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusMigration.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "loopedTransitionContainerLayout", n => { LoopedTransitionContainerLayout = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowLayout>(global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowLayout.CreateFromDiscriminatorValue); } },
                { "startPointLayout", n => { StartPointLayout = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowLayout>(global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowLayout.CreateFromDiscriminatorValue); } },
                { "statusMappings", n => { StatusMappings = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusMappingDTO>(global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusMappingDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "statuses", n => { Statuses = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusLayoutUpdate>(global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusLayoutUpdate.CreateFromDiscriminatorValue)?.AsList(); } },
                { "transitions", n => { Transitions = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.TransitionUpdateDTO>(global::Kubis1982.Atlassian.Jira.RestClient.Models.TransitionUpdateDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "version", n => { Version = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.DocumentVersion>(global::Kubis1982.Atlassian.Jira.RestClient.Models.DocumentVersion.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusMigration>("defaultStatusMappings", DefaultStatusMappings);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowLayout>("loopedTransitionContainerLayout", LoopedTransitionContainerLayout);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowLayout>("startPointLayout", StartPointLayout);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusLayoutUpdate>("statuses", Statuses);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.StatusMappingDTO>("statusMappings", StatusMappings);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.TransitionUpdateDTO>("transitions", Transitions);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.DocumentVersion>("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
