// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>
    /// The create workflows payload.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowCreateRequest : IParsable
    {
        /// <summary>The scope of the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowScope? Scope { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowScope Scope { get; set; }
#endif
        /// <summary>The statuses to associate with the workflows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowStatusUpdate>? Statuses { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowStatusUpdate> Statuses { get; set; }
#endif
        /// <summary>The details of the workflows to create.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowCreate>? Workflows { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowCreate> Workflows { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "scope", n => { Scope = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowScope>(global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowScope.CreateFromDiscriminatorValue); } },
                { "statuses", n => { Statuses = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowStatusUpdate>(global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowStatusUpdate.CreateFromDiscriminatorValue)?.AsList(); } },
                { "workflows", n => { Workflows = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowCreate>(global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowCreate.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowScope>("scope", Scope);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowStatusUpdate>("statuses", Statuses);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowCreate>("workflows", Workflows);
        }
    }
}
#pragma warning restore CS0618
