// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Models
{
    /// <summary>
    /// A list of workflow history entries.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowHistoryListResponseDTO : IParsable
    {
        /// <summary>The entries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowHistoryItemDTO>? Entries { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowHistoryItemDTO> Entries { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowHistoryListResponseDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowHistoryListResponseDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowHistoryListResponseDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entries", n => { Entries = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowHistoryItemDTO>(global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowHistoryItemDTO.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowHistoryItemDTO>("entries", Entries);
        }
    }
}
#pragma warning restore CS0618
