// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Jira.RestClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Workflowscheme.Read
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\3\workflowscheme\read
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Workflowscheme.Read.ReadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/workflowscheme/read", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Workflowscheme.Read.ReadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/workflowscheme/read", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of workflow schemes by providing workflow scheme IDs or project IDs.**[Permissions](#permissions) required:** *  *Administer Jira* global permission to access all, including project-scoped, workflow schemes *  *Administer projects* project permissions to access project-scoped workflow schemes
        /// </summary>
        /// <returns>A List&lt;global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowSchemeReadResponse&gt;</returns>
        /// <param name="body">The workflow scheme read request body.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowSchemeReadResponse>?> PostAsync(global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowSchemeReadRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowSchemeReadResponse>> PostAsync(global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowSchemeReadRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowSchemeReadResponse>(requestInfo, global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowSchemeReadResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Returns a list of workflow schemes by providing workflow scheme IDs or project IDs.**[Permissions](#permissions) required:** *  *Administer Jira* global permission to access all, including project-scoped, workflow schemes *  *Administer projects* project permissions to access project-scoped workflow schemes
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The workflow scheme read request body.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowSchemeReadRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Kubis1982.Atlassian.Jira.RestClient.Models.WorkflowSchemeReadRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Workflowscheme.Read.ReadRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Workflowscheme.Read.ReadRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Workflowscheme.Read.ReadRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReadRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
