// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Jira.RestClient.Models;
using Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.EditTemplate;
using Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.LiveTemplate;
using Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.RemoveTemplate;
using Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.SaveTemplate;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\3\project-template
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectTemplateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The editTemplate property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.EditTemplate.EditTemplateRequestBuilder EditTemplate
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.EditTemplate.EditTemplateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The liveTemplate property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.LiveTemplate.LiveTemplateRequestBuilder LiveTemplate
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.LiveTemplate.LiveTemplateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The removeTemplate property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.RemoveTemplate.RemoveTemplateRequestBuilder RemoveTemplate
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.RemoveTemplate.RemoveTemplateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The saveTemplate property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.SaveTemplate.SaveTemplateRequestBuilder SaveTemplate
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.SaveTemplate.SaveTemplateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.ProjectTemplateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectTemplateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/project-template", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.ProjectTemplateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectTemplateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/project-template", rawUrl)
        {
        }
        /// <summary>
        /// Creates a project based on a custom template provided in the request.The request body should contain the project details and the capabilities that comprise the project: *  `details` \- represents the project details settings *  `template` \- represents a list of capabilities responsible for creating specific parts of a projectA capability is defined as a unit of configuration for the project you want to create.This operation is: *  [asynchronous](#async). Follow the `Location` link in the response header to determine the status of the task and use [Get task](#api-rest-api-3-task-taskId-get) to obtain subsequent updates.***Note: This API is only supported for Jira Enterprise edition.*****[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        /// </summary>
        /// <param name="body">Request to create a project using a custom template</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectCustomTemplateCreateRequestDTO body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectCustomTemplateCreateRequestDTO body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a project based on a custom template provided in the request.The request body should contain the project details and the capabilities that comprise the project: *  `details` \- represents the project details settings *  `template` \- represents a list of capabilities responsible for creating specific parts of a projectA capability is defined as a unit of configuration for the project you want to create.This operation is: *  [asynchronous](#async). Follow the `Location` link in the response header to determine the status of the task and use [Get task](#api-rest-api-3-task-taskId-get) to obtain subsequent updates.***Note: This API is only supported for Jira Enterprise edition.*****[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request to create a project using a custom template</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectCustomTemplateCreateRequestDTO body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Kubis1982.Atlassian.Jira.RestClient.Models.ProjectCustomTemplateCreateRequestDTO body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.ProjectTemplateRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.ProjectTemplateRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.ProjectTemplate.ProjectTemplateRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectTemplateRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
