// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Confluense.RestClient.Spaces
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SpacesPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>This field will be used as the new identifier for the space in confluence page URLs. If the alias property is not provided, the key property is required to be used instead. Maximum 255 alphanumeric characters in length.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Alias { get; set; }
#nullable restore
#else
        public string Alias { get; set; }
#endif
        /// <summary>The id of the space to copy the space access configuration from.</summary>
        public int? CopySpaceAccessConfiguration { get; set; }
        /// <summary>Whether to create the space as private.</summary>
        public bool? CreatePrivateSpace { get; set; }
        /// <summary>The description of the new/updated space. Note, only the &apos;plain&apos; representation is currently supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody_description? Description { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody_description Description { get; set; }
#endif
        /// <summary>The key for the new space. See [Space Keys](https://support.atlassian.com/confluence-cloud/docs/create-a-space/). If the key property is not provided, the alias property is required to be used instead.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The name of the space to be created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The roleAssignments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody_roleAssignments>? RoleAssignments { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody_roleAssignments> RoleAssignments { get; set; }
#endif
        /// <summary>The key of the template to use.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateKey { get; set; }
#nullable restore
#else
        public string TemplateKey { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody"/> and sets the default values.
        /// </summary>
        public SpacesPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alias", n => { Alias = n.GetStringValue(); } },
                { "copySpaceAccessConfiguration", n => { CopySpaceAccessConfiguration = n.GetIntValue(); } },
                { "createPrivateSpace", n => { CreatePrivateSpace = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetObjectValue<global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody_description>(global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody_description.CreateFromDiscriminatorValue); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "roleAssignments", n => { RoleAssignments = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody_roleAssignments>(global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody_roleAssignments.CreateFromDiscriminatorValue)?.AsList(); } },
                { "templateKey", n => { TemplateKey = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alias", Alias);
            writer.WriteIntValue("copySpaceAccessConfiguration", CopySpaceAccessConfiguration);
            writer.WriteBoolValue("createPrivateSpace", CreatePrivateSpace);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody_description>("description", Description);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Confluense.RestClient.Spaces.SpacesPostRequestBody_roleAssignments>("roleAssignments", RoleAssignments);
            writer.WriteStringValue("templateKey", TemplateKey);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
