// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item.Project;
using Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item.ProjectUsages;
using Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item.WorkflowUsages;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\2\statuses\{statusId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithStatusItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The project property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item.Project.ProjectRequestBuilder Project
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item.Project.ProjectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projectUsages property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item.ProjectUsages.ProjectUsagesRequestBuilder ProjectUsages
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item.ProjectUsages.ProjectUsagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workflowUsages property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item.WorkflowUsages.WorkflowUsagesRequestBuilder WorkflowUsages
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item.WorkflowUsages.WorkflowUsagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item.WithStatusItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithStatusItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/2/statuses/{statusId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Statuses.Item.WithStatusItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithStatusItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/2/statuses/{statusId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
