// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.AccessRemovals;
using Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.Combinations;
using Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.RoleAssignments;
using Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.Tasks;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition
{
    /// <summary>
    /// Builds and executes requests for operations under \space-permissions\transition
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransitionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accessRemovals property</summary>
        public global::Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.AccessRemovals.AccessRemovalsRequestBuilder AccessRemovals
        {
            get => new global::Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.AccessRemovals.AccessRemovalsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The combinations property</summary>
        public global::Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.Combinations.CombinationsRequestBuilder Combinations
        {
            get => new global::Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.Combinations.CombinationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roleAssignments property</summary>
        public global::Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.RoleAssignments.RoleAssignmentsRequestBuilder RoleAssignments
        {
            get => new global::Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.RoleAssignments.RoleAssignmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tasks property</summary>
        public global::Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.TransitionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransitionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/space-permissions/transition", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.SpacePermissions.Transition.TransitionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransitionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/space-permissions/transition", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
