// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Bitbucket.RestClient.Models
{
    /// <summary>
    /// Base type for most resource objects. It defines the common `type` element that identifies an object&apos;s type. It also identifies the element as Swagger&apos;s `discriminator`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ObjectObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.ObjectObject"/> and sets the default values.
        /// </summary>
        public ObjectObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.ObjectObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.ObjectObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            return mappingValue switch
            {
                "account" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Account(),
                "app_user" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.App_user(),
                "author" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Author(),
                "base_commit" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Base_commit(),
                "branching_model" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Branching_model(),
                "branching_model_settings" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Branching_model_settings(),
                "branchrestriction" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Branchrestriction(),
                "comment" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Comment(),
                "commit" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Commit(),
                "commitstatus" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Commitstatus(),
                "committer" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Committer(),
                "commit_comment" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Commit_comment(),
                "component" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Component(),
                "deployment" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment(),
                "deployment_environment" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment_environment(),
                "deployment_release" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment_release(),
                "deployment_state" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment_state(),
                "deployment_state_completed" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment_state_completed(),
                "deployment_state_completed_status" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment_state_completed_status(),
                "deployment_state_completed_status_failed" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment_state_completed_status_failed(),
                "deployment_state_completed_status_stopped" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment_state_completed_status_stopped(),
                "deployment_state_completed_status_successful" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment_state_completed_status_successful(),
                "deployment_state_in_progress" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment_state_in_progress(),
                "deployment_state_undeployed" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment_state_undeployed(),
                "deployment_variable" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deployment_variable(),
                "deploy_key" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Deploy_key(),
                "effective_repo_branching_model" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Effective_repo_branching_model(),
                "GPG_account_key" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.GPG_account_key(),
                "group" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Group(),
                "issue" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Issue(),
                "issue_attachment" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Issue_attachment(),
                "issue_comment" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Issue_comment(),
                "milestone" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Milestone(),
                "participant" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Participant(),
                "pipeline" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline(),
                "pipelines_config" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipelines_config(),
                "pipelines_links_section_href" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipelines_links_section_href(),
                "pipelines_pipeline_links" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipelines_pipeline_links(),
                "pipeline_build_number" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_build_number(),
                "pipeline_cache" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_cache(),
                "pipeline_commit_target" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_commit_target(),
                "pipeline_error" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_error(),
                "pipeline_known_host" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_known_host(),
                "pipeline_ref_target" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_ref_target(),
                "pipeline_runner" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_runner(),
                "pipeline_runner_oauth_client" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_runner_oauth_client(),
                "pipeline_runner_state" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_runner_state(),
                "pipeline_runner_version" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_runner_version(),
                "pipeline_schedule" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_schedule(),
                "pipeline_schedule_execution" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_schedule_execution(),
                "pipeline_schedule_execution_errored" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_schedule_execution_errored(),
                "pipeline_schedule_execution_executed" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_schedule_execution_executed(),
                "pipeline_schedule_post_request_body" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_schedule_post_request_body(),
                "pipeline_schedule_put_request_body" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_schedule_put_request_body(),
                "pipeline_selector" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_selector(),
                "pipeline_ssh_key_pair" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_ssh_key_pair(),
                "pipeline_ssh_public_key" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_ssh_public_key(),
                "pipeline_state" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state(),
                "pipeline_state_completed" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_completed(),
                "pipeline_state_completed_error" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_completed_error(),
                "pipeline_state_completed_expired" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_completed_expired(),
                "pipeline_state_completed_failed" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_completed_failed(),
                "pipeline_state_completed_result" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_completed_result(),
                "pipeline_state_completed_stopped" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_completed_stopped(),
                "pipeline_state_completed_successful" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_completed_successful(),
                "pipeline_state_in_progress" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_in_progress(),
                "pipeline_state_in_progress_paused" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_in_progress_paused(),
                "pipeline_state_in_progress_running" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_in_progress_running(),
                "pipeline_state_in_progress_stage" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_in_progress_stage(),
                "pipeline_state_pending" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_state_pending(),
                "pipeline_step" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step(),
                "pipeline_step_error" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_error(),
                "pipeline_step_state" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state(),
                "pipeline_step_state_completed" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state_completed(),
                "pipeline_step_state_completed_error" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state_completed_error(),
                "pipeline_step_state_completed_expired" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state_completed_expired(),
                "pipeline_step_state_completed_failed" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state_completed_failed(),
                "pipeline_step_state_completed_not_run" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state_completed_not_run(),
                "pipeline_step_state_completed_result" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state_completed_result(),
                "pipeline_step_state_completed_stopped" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state_completed_stopped(),
                "pipeline_step_state_completed_successful" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state_completed_successful(),
                "pipeline_step_state_in_progress" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state_in_progress(),
                "pipeline_step_state_pending" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state_pending(),
                "pipeline_step_state_ready" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_step_state_ready(),
                "pipeline_target" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_target(),
                "pipeline_trigger" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_trigger(),
                "pipeline_trigger_manual" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_trigger_manual(),
                "pipeline_trigger_push" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_trigger_push(),
                "pipeline_variable" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pipeline_variable(),
                "project" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Project(),
                "project_branching_model" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Project_branching_model(),
                "project_deploy_key" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Project_deploy_key(),
                "pullrequest" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pullrequest(),
                "pullrequest_comment" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Pullrequest_comment(),
                "report" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Report(),
                "report_annotation" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Report_annotation(),
                "repository" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Repository(),
                "snippet" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Snippet(),
                "snippet_comment" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Snippet_comment(),
                "snippet_commit" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Snippet_commit(),
                "ssh_account_key" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Ssh_account_key(),
                "ssh_key" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Ssh_key(),
                "team" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Team(),
                "user" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.User(),
                "version" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.VersionObject(),
                "webhook_subscription" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Webhook_subscription(),
                "workspace" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Workspace(),
                "workspace_access" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Workspace_access(),
                "workspace_base" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Workspace_base(),
                "workspace_membership" => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.Workspace_membership(),
                _ => new global::Kubis1982.Atlassian.Bitbucket.RestClient.Models.ObjectObject(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
