// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Bitbucket.RestClient.Models
{
    /// <summary>The type of the report.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Report_report_type
    {
        [EnumMember(Value = "SECURITY")]
        #pragma warning disable CS1591
        SECURITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "COVERAGE")]
        #pragma warning disable CS1591
        COVERAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEST")]
        #pragma warning disable CS1591
        TEST,
        #pragma warning restore CS1591
        [EnumMember(Value = "BUG")]
        #pragma warning disable CS1591
        BUG,
        #pragma warning restore CS1591
    }
}
