// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Confluense.RestClient.Models
{
    /// <summary>The status of the content.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ContentStatus
    {
        [EnumMember(Value = "current")]
        #pragma warning disable CS1591
        Current,
        #pragma warning restore CS1591
        [EnumMember(Value = "draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "archived")]
        #pragma warning disable CS1591
        Archived,
        #pragma warning restore CS1591
        [EnumMember(Value = "historical")]
        #pragma warning disable CS1591
        Historical,
        #pragma warning restore CS1591
        [EnumMember(Value = "trashed")]
        #pragma warning disable CS1591
        Trashed,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "any")]
        #pragma warning disable CS1591
        Any,
        #pragma warning restore CS1591
    }
}
