// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Confluense.RestClient.Models
{
    /// <summary>The formats a custom content body can be represented as. A subset of BodyRepresentation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomContentBodyRepresentation
    {
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
        [EnumMember(Value = "storage")]
        #pragma warning disable CS1591
        Storage,
        #pragma warning restore CS1591
        [EnumMember(Value = "atlas_doc_format")]
        #pragma warning disable CS1591
        Atlas_doc_format,
        #pragma warning restore CS1591
    }
}
