// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Confluense.RestClient.Models
{
    /// <summary>Inline comment resolution status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InlineCommentResolutionStatus
    {
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "reopened")]
        #pragma warning disable CS1591
        Reopened,
        #pragma warning restore CS1591
        [EnumMember(Value = "resolved")]
        #pragma warning disable CS1591
        Resolved,
        #pragma warning restore CS1591
        [EnumMember(Value = "dangling")]
        #pragma warning disable CS1591
        Dangling,
        #pragma warning restore CS1591
    }
}
