// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Confluense.RestClient.Models
{
    /// <summary>The sort fields for spaces. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SpaceSortOrder
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "-id")]
        #pragma warning disable CS1591
        Minus_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "key")]
        #pragma warning disable CS1591
        Key,
        #pragma warning restore CS1591
        [EnumMember(Value = "-key")]
        #pragma warning disable CS1591
        Minus_key,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "-name")]
        #pragma warning disable CS1591
        Minus_name,
        #pragma warning restore CS1591
    }
}
