// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Models
{
    /// <summary>The operator between the clauses.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CompoundClause_operator
    {
        [EnumMember(Value = "and")]
        #pragma warning disable CS1591
        And,
        #pragma warning restore CS1591
        [EnumMember(Value = "or")]
        #pragma warning disable CS1591
        Or,
        #pragma warning restore CS1591
        [EnumMember(Value = "not")]
        #pragma warning disable CS1591
        Not,
        #pragma warning restore CS1591
    }
}
