// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Models
{
    /// <summary>
    /// Details about the project.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateProjectDetails : IParsable
    {
        /// <summary>The default assignee when creating issues for this project.</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails_assigneeType? AssigneeType { get; set; }
        /// <summary>An integer value for the project&apos;s avatar.</summary>
        public long? AvatarId { get; set; }
        /// <summary>The ID of the project&apos;s category. A complete list of category IDs is found using the [Get all project categories](#api-rest-api-2-projectCategory-get) operation.</summary>
        public long? CategoryId { get; set; }
        /// <summary>A brief description of the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Deprecated use [fieldScheme](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-field-schemes/#api-group-field-schemes) instead. The ID of the field configuration scheme for the project. Use the [Get all field configuration schemes](#api-rest-api-2-fieldconfigurationscheme-get) operation to get a list of field configuration scheme IDs. If you specify the field configuration scheme you cannot specify the project template key.</summary>
        [Obsolete("")]
        public long? FieldConfigurationScheme { get; set; }
        /// <summary>The ID of the field scheme for the project. Use the [Get field schemes](#api-rest-api-2-config-fieldschemes-get) operation to get a list of field scheme IDs. If you specify the field scheme you cannot specify the project template key.</summary>
        public long? FieldScheme { get; set; }
        /// <summary>The ID of the issue security scheme for the project, which enables you to control who can and cannot view issues. Use the [Get issue security schemes](#api-rest-api-2-issuesecurityschemes-get) resource to get all issue security scheme IDs.</summary>
        public long? IssueSecurityScheme { get; set; }
        /// <summary>The ID of the issue type scheme for the project. Use the [Get all issue type schemes](#api-rest-api-2-issuetypescheme-get) operation to get a list of issue type scheme IDs. If you specify the issue type scheme you cannot specify the project template key.</summary>
        public long? IssueTypeScheme { get; set; }
        /// <summary>The ID of the issue type screen scheme for the project. Use the [Get all issue type screen schemes](#api-rest-api-2-issuetypescreenscheme-get) operation to get a list of issue type screen scheme IDs. If you specify the issue type screen scheme you cannot specify the project template key.</summary>
        public long? IssueTypeScreenScheme { get; set; }
        /// <summary>Project keys must be unique and start with an uppercase letter followed by one or more uppercase alphanumeric characters. The maximum length is 10 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>This parameter is deprecated because of privacy changes. Use `leadAccountId` instead. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. The user name of the project lead. Either `lead` or `leadAccountId` must be set when creating a project. Cannot be provided with `leadAccountId`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lead { get; set; }
#nullable restore
#else
        public string Lead { get; set; }
#endif
        /// <summary>The account ID of the project lead. Either `lead` or `leadAccountId` must be set when creating a project. Cannot be provided with `lead`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadAccountId { get; set; }
#nullable restore
#else
        public string LeadAccountId { get; set; }
#endif
        /// <summary>The name of the project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ID of the notification scheme for the project. Use the [Get notification schemes](#api-rest-api-2-notificationscheme-get) resource to get a list of notification scheme IDs.</summary>
        public long? NotificationScheme { get; set; }
        /// <summary>The ID of the permission scheme for the project. Use the [Get all permission schemes](#api-rest-api-2-permissionscheme-get) resource to see a list of all permission scheme IDs.</summary>
        public long? PermissionScheme { get; set; }
        /// <summary>A predefined configuration for a project. The type of the `projectTemplateKey` must match with the type of the `projectTypeKey`.</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails_projectTemplateKey? ProjectTemplateKey { get; set; }
        /// <summary>The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes), which defines the application-specific feature set. If you don&apos;t specify the project template you have to specify the project type.</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails_projectTypeKey? ProjectTypeKey { get; set; }
        /// <summary>A link to information about this project, such as project documentation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The ID of the workflow scheme for the project. Use the [Get all workflow schemes](#api-rest-api-2-workflowscheme-get) operation to get a list of workflow scheme IDs. If you specify the workflow scheme you cannot specify the project template key.</summary>
        public long? WorkflowScheme { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assigneeType", n => { AssigneeType = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails_assigneeType>(); } },
                { "avatarId", n => { AvatarId = n.GetLongValue(); } },
                { "categoryId", n => { CategoryId = n.GetLongValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "fieldConfigurationScheme", n => { FieldConfigurationScheme = n.GetLongValue(); } },
                { "fieldScheme", n => { FieldScheme = n.GetLongValue(); } },
                { "issueSecurityScheme", n => { IssueSecurityScheme = n.GetLongValue(); } },
                { "issueTypeScheme", n => { IssueTypeScheme = n.GetLongValue(); } },
                { "issueTypeScreenScheme", n => { IssueTypeScreenScheme = n.GetLongValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "lead", n => { Lead = n.GetStringValue(); } },
                { "leadAccountId", n => { LeadAccountId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notificationScheme", n => { NotificationScheme = n.GetLongValue(); } },
                { "permissionScheme", n => { PermissionScheme = n.GetLongValue(); } },
                { "projectTemplateKey", n => { ProjectTemplateKey = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails_projectTemplateKey>(); } },
                { "projectTypeKey", n => { ProjectTypeKey = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails_projectTypeKey>(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "workflowScheme", n => { WorkflowScheme = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails_assigneeType>("assigneeType", AssigneeType);
            writer.WriteLongValue("avatarId", AvatarId);
            writer.WriteLongValue("categoryId", CategoryId);
            writer.WriteStringValue("description", Description);
            writer.WriteLongValue("fieldConfigurationScheme", FieldConfigurationScheme);
            writer.WriteLongValue("fieldScheme", FieldScheme);
            writer.WriteLongValue("issueSecurityScheme", IssueSecurityScheme);
            writer.WriteLongValue("issueTypeScheme", IssueTypeScheme);
            writer.WriteLongValue("issueTypeScreenScheme", IssueTypeScreenScheme);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("lead", Lead);
            writer.WriteStringValue("leadAccountId", LeadAccountId);
            writer.WriteStringValue("name", Name);
            writer.WriteLongValue("notificationScheme", NotificationScheme);
            writer.WriteLongValue("permissionScheme", PermissionScheme);
            writer.WriteEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails_projectTemplateKey>("projectTemplateKey", ProjectTemplateKey);
            writer.WriteEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.CreateProjectDetails_projectTypeKey>("projectTypeKey", ProjectTypeKey);
            writer.WriteStringValue("url", Url);
            writer.WriteLongValue("workflowScheme", WorkflowScheme);
        }
    }
}
#pragma warning restore CS0618
