// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Models
{
    /// <summary>Allows an overwrite to declare the new Custom Field to be created as a GLOBAL-scoped field. Leave this as empty or null to use the project&apos;s default scope.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomFieldPayload_scope
    {
        [EnumMember(Value = "GLOBAL")]
        #pragma warning disable CS1591
        GLOBAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEMPLATE")]
        #pragma warning disable CS1591
        TEMPLATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROJECT")]
        #pragma warning disable CS1591
        PROJECT,
        #pragma warning restore CS1591
    }
}
