// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Models
{
    /// <summary>
    /// The list of users found in a search, including header text (Showing X of Y matching users) and total of matched users.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FoundUsers : IParsable
    {
        /// <summary>Header text indicating the number of users in the response and the total number of users found in the search.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Header { get; set; }
#nullable restore
#else
        public string Header { get; set; }
#endif
        /// <summary>The total number of users found in the search.</summary>
        public int? Total { get; set; }
        /// <summary>The users property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.UserPickerUser>? Users { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.UserPickerUser> Users { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundUsers"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundUsers CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundUsers();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "header", n => { Header = n.GetStringValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
                { "users", n => { Users = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.UserPickerUser>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.UserPickerUser.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("header", Header);
            writer.WriteIntValue("total", Total);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.UserPickerUser>("users", Users);
        }
    }
}
#pragma warning restore CS0618
