// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Models
{
    /// <summary>
    /// List of users and groups found in a search.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FoundUsersAndGroups : IParsable
    {
        /// <summary>The list of groups found in a search, including header text (Showing X of Y matching groups) and total of matched groups.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundGroups? Groups { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundGroups Groups { get; set; }
#endif
        /// <summary>The list of users found in a search, including header text (Showing X of Y matching users) and total of matched users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundUsers? Users { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundUsers Users { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundUsersAndGroups"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundUsersAndGroups CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundUsersAndGroups();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "groups", n => { Groups = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundGroups>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundGroups.CreateFromDiscriminatorValue); } },
                { "users", n => { Users = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundUsers>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundUsers.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundGroups>("groups", Groups);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.FoundUsers>("users", Users);
        }
    }
}
#pragma warning restore CS0618
