// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Models
{
    /// <summary>The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProjectDetails_projectTypeKey
    {
        [EnumMember(Value = "software")]
        #pragma warning disable CS1591
        Software,
        #pragma warning restore CS1591
        [EnumMember(Value = "service_desk")]
        #pragma warning disable CS1591
        Service_desk,
        #pragma warning restore CS1591
        [EnumMember(Value = "business")]
        #pragma warning disable CS1591
        Business,
        #pragma warning restore CS1591
    }
}
