// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Models
{
    /// <summary>
    /// The payload used to create a project role. It is optional for CMP projects, as a default role actor will be provided. TMP will add new role actors to the table.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RolePayload : IParsable
    {
        /// <summary>The default actors for the role. By adding default actors, the role will be added to any future projects created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ProjectCreateResourceIdentifier>? DefaultActors { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ProjectCreateResourceIdentifier> DefaultActors { get; set; }
#endif
        /// <summary>The description of the role</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The name of the role</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The strategy to use when there is a conflict with an existing project role. FAIL - Fail execution, this always needs to be unique; USE - Use the existing entity and ignore new entity parameters</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RolePayload_onConflict? OnConflict { get; set; }
        /// <summary>Every project-created entity has an ID that must be unique within the scope of the project creation. PCRI (Project Create Resource Identifier) is a standard format for creating IDs and references to other project entities. PCRI format is defined as follows: pcri:\[entityType\]:\[type\]:\[entityId\] entityType - the type of an entity, e.g. status, role, workflow type - PCRI type, either `id` - The ID of an entity that already exists in the target site, or `ref` - A unique reference to an entity that is being created entityId - entity identifier, if type is `id` - must be an existing entity ID that exists in the Jira site, if `ref` - must be unique across all entities in the scope of this project template creation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ProjectCreateResourceIdentifier? Pcri { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ProjectCreateResourceIdentifier Pcri { get; set; }
#endif
        /// <summary>The type of the role. Only used by project-scoped project</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RolePayload_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RolePayload"/> and sets the default values.
        /// </summary>
        public RolePayload()
        {
            OnConflict = global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RolePayload_onConflict.USE;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RolePayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RolePayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RolePayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "defaultActors", n => { DefaultActors = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ProjectCreateResourceIdentifier>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ProjectCreateResourceIdentifier.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "onConflict", n => { OnConflict = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RolePayload_onConflict>(); } },
                { "pcri", n => { Pcri = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ProjectCreateResourceIdentifier>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ProjectCreateResourceIdentifier.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RolePayload_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ProjectCreateResourceIdentifier>("defaultActors", DefaultActors);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RolePayload_onConflict>("onConflict", OnConflict);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ProjectCreateResourceIdentifier>("pcri", Pcri);
            writer.WriteEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RolePayload_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
