// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Models
{
    /// <summary>
    /// The transition update data.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransitionUpdateDTO : IAdditionalDataHolder, IParsable
    {
        /// <summary>The post-functions of the transition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration>? Actions { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration> Actions { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The conditions group associated with the transition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ConditionGroupUpdate? Conditions { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ConditionGroupUpdate Conditions { get; set; }
#endif
        /// <summary>The custom event ID of the transition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomIssueEventId { get; set; }
#nullable restore
#else
        public string CustomIssueEventId { get; set; }
#endif
        /// <summary>The description of the transition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The ID of the transition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The statuses the transition can start from, and the mapping of ports between the statuses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowTransitionLinks>? Links { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowTransitionLinks> Links { get; set; }
#endif
        /// <summary>The name of the transition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The properties of the transition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO_properties? Properties { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO_properties Properties { get; set; }
#endif
        /// <summary>The status the transition goes to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToStatusReference { get; set; }
#nullable restore
#else
        public string ToStatusReference { get; set; }
#endif
        /// <summary>The configuration of the rule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration? TransitionScreen { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration TransitionScreen { get; set; }
#endif
        /// <summary>The triggers of the transition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowTrigger>? Triggers { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowTrigger> Triggers { get; set; }
#endif
        /// <summary>The transition type.</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO_type? Type { get; set; }
        /// <summary>The validators of the transition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration>? Validators { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration> Validators { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO"/> and sets the default values.
        /// </summary>
        public TransitionUpdateDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actions", n => { Actions = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration.CreateFromDiscriminatorValue)?.AsList(); } },
                { "conditions", n => { Conditions = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ConditionGroupUpdate>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ConditionGroupUpdate.CreateFromDiscriminatorValue); } },
                { "customIssueEventId", n => { CustomIssueEventId = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowTransitionLinks>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowTransitionLinks.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "properties", n => { Properties = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO_properties>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO_properties.CreateFromDiscriminatorValue); } },
                { "toStatusReference", n => { ToStatusReference = n.GetStringValue(); } },
                { "transitionScreen", n => { TransitionScreen = n.GetObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration.CreateFromDiscriminatorValue); } },
                { "triggers", n => { Triggers = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowTrigger>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowTrigger.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO_type>(); } },
                { "validators", n => { Validators = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration>("actions", Actions);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ConditionGroupUpdate>("conditions", Conditions);
            writer.WriteStringValue("customIssueEventId", CustomIssueEventId);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowTransitionLinks>("links", Links);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO_properties>("properties", Properties);
            writer.WriteStringValue("toStatusReference", ToStatusReference);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration>("transitionScreen", TransitionScreen);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowTrigger>("triggers", Triggers);
            writer.WriteEnumValue<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.TransitionUpdateDTO_type>("type", Type);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowRuleConfiguration>("validators", Validators);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
