// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Models
{
    /// <summary>
    /// A list of webhooks.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebhookDetails : IParsable
    {
        /// <summary>The Jira events that trigger the webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WebhookDetails_events?>? Events { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WebhookDetails_events?> Events { get; set; }
#endif
        /// <summary>A list of field IDs. When the issue changelog contains any of the fields, the webhook `jira:issue_updated` is sent. If this parameter is not present, the app is notified about all field updates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FieldIdsFilter { get; set; }
#nullable restore
#else
        public List<string> FieldIdsFilter { get; set; }
#endif
        /// <summary>A list of issue property keys. A change of those issue properties triggers the `issue_property_set` or `issue_property_deleted` webhooks. If this parameter is not present, the app is notified about all issue property updates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IssuePropertyKeysFilter { get; set; }
#nullable restore
#else
        public List<string> IssuePropertyKeysFilter { get; set; }
#endif
        /// <summary>The JQL filter that specifies which issues the webhook is sent for. Only a subset of JQL can be used. The supported elements are: *  Fields: `issueKey`, `project`, `issuetype`, `status`, `assignee`, `reporter`, `issue.property`, and `cf[id]`. For custom fields (`cf[id]`), only the epic label custom field is supported.&quot;. *  Operators: `=`, `!=`, `IN`, and `NOT IN`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JqlFilter { get; set; }
#nullable restore
#else
        public string JqlFilter { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WebhookDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WebhookDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WebhookDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "events", n => { Events = n.GetCollectionOfEnumValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WebhookDetails_events>()?.AsList(); } },
                { "fieldIdsFilter", n => { FieldIdsFilter = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "issuePropertyKeysFilter", n => { IssuePropertyKeysFilter = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "jqlFilter", n => { JqlFilter = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WebhookDetails_events>("events", Events);
            writer.WriteCollectionOfPrimitiveValues<string>("fieldIdsFilter", FieldIdsFilter);
            writer.WriteCollectionOfPrimitiveValues<string>("issuePropertyKeysFilter", IssuePropertyKeysFilter);
            writer.WriteStringValue("jqlFilter", JqlFilter);
        }
    }
}
#pragma warning restore CS0618
