// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WorkflowSchemeUpdateRequiredMappingsResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The details of the statuses in the associated workflows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StatusMetadata>? Statuses { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StatusMetadata> Statuses { get; set; }
#endif
        /// <summary>The statuses associated with each workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StatusesPerWorkflow>? StatusesPerWorkflow { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StatusesPerWorkflow> StatusesPerWorkflow { get; set; }
#endif
        /// <summary>The list of required status mappings by issue type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RequiredMappingByIssueType>? StatusMappingsByIssueTypes { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RequiredMappingByIssueType> StatusMappingsByIssueTypes { get; set; }
#endif
        /// <summary>The list of required status mappings by workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RequiredMappingByWorkflows>? StatusMappingsByWorkflows { get; set; }
#nullable restore
#else
        public List<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RequiredMappingByWorkflows> StatusMappingsByWorkflows { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowSchemeUpdateRequiredMappingsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowSchemeUpdateRequiredMappingsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.WorkflowSchemeUpdateRequiredMappingsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "statusMappingsByIssueTypes", n => { StatusMappingsByIssueTypes = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RequiredMappingByIssueType>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RequiredMappingByIssueType.CreateFromDiscriminatorValue)?.AsList(); } },
                { "statusMappingsByWorkflows", n => { StatusMappingsByWorkflows = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RequiredMappingByWorkflows>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RequiredMappingByWorkflows.CreateFromDiscriminatorValue)?.AsList(); } },
                { "statuses", n => { Statuses = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StatusMetadata>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StatusMetadata.CreateFromDiscriminatorValue)?.AsList(); } },
                { "statusesPerWorkflow", n => { StatusesPerWorkflow = n.GetCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StatusesPerWorkflow>(global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StatusesPerWorkflow.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StatusMetadata>("statuses", Statuses);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StatusesPerWorkflow>("statusesPerWorkflow", StatusesPerWorkflow);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RequiredMappingByIssueType>("statusMappingsByIssueTypes", StatusMappingsByIssueTypes);
            writer.WriteCollectionOfObjectValues<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.RequiredMappingByWorkflows>("statusMappingsByWorkflows", StatusMappingsByWorkflows);
        }
    }
}
#pragma warning restore CS0618
