// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Bulk.Queue.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Bulk.Queue
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\3\bulk\queue
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QueueRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Kubis1982.Atlassian.Jira.RestClient.rest.api.Three.bulk.queue.item collection</summary>
        /// <param name="position">The ID of the task.</param>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Bulk.Queue.Item.WithTaskItemRequestBuilder"/></returns>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Bulk.Queue.Item.WithTaskItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("taskId", position);
                return new global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Bulk.Queue.Item.WithTaskItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Bulk.Queue.QueueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueueRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/bulk/queue", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Bulk.Queue.QueueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueueRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/bulk/queue", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
