// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Jira.RestClient.V2.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\2\universal_avatar\view\type\{type}\owner\{entityId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEntityItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.WithEntityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/2/universal_avatar/view/type/{type}/owner/{entityId}{?format*,size*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.WithEntityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/2/universal_avatar/view/type/{type}/owner/{entityId}{?format*,size*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the avatar image for a project, issue type or priority.This operation can be accessed anonymously.**[Permissions](#permissions) required:** *  For system avatars, none. *  For custom project avatars, *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project the avatar belongs to. *  For custom issue type avatars, *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for at least one project the issue type is used in. *  For priority avatars, none.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StreamingResponseBody"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection">When receiving a 400 status code</exception>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection">When receiving a 401 status code</exception>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection">When receiving a 403 status code</exception>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StreamingResponseBody?> GetAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.WithEntityItemRequestBuilder.WithEntityItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StreamingResponseBody> GetAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.WithEntityItemRequestBuilder.WithEntityItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection.CreateFromDiscriminatorValue },
                { "401", global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection.CreateFromDiscriminatorValue },
                { "403", global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection.CreateFromDiscriminatorValue },
                { "404", global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StreamingResponseBody>(requestInfo, global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.StreamingResponseBody.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the avatar image for a project, issue type or priority.This operation can be accessed anonymously.**[Permissions](#permissions) required:** *  For system avatars, none. *  For custom project avatars, *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project the avatar belongs to. *  For custom issue type avatars, *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for at least one project the issue type is used in. *  For priority avatars, none.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.WithEntityItemRequestBuilder.WithEntityItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.WithEntityItemRequestBuilder.WithEntityItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.WithEntityItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.WithEntityItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.WithEntityItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the avatar image for a project, issue type or priority.This operation can be accessed anonymously.**[Permissions](#permissions) required:** *  For system avatars, none. *  For custom project avatars, *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project the avatar belongs to. *  For custom issue type avatars, *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for at least one project the issue type is used in. *  For priority avatars, none.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithEntityItemRequestBuilderGetQueryParameters 
        {
            /// <summary>The format to return the avatar image in. If not provided the original content format is returned.</summary>
            [Obsolete("This property is deprecated, use FormatAsGetFormatQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("format")]
            public string? Format { get; set; }
#nullable restore
#else
            [QueryParameter("format")]
            public string Format { get; set; }
#endif
            /// <summary>The format to return the avatar image in. If not provided the original content format is returned.</summary>
            [QueryParameter("format")]
            public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.GetFormatQueryParameterType? FormatAsGetFormatQueryParameterType { get; set; }
            /// <summary>The size of the avatar image. If not provided the default size is returned.</summary>
            [Obsolete("This property is deprecated, use SizeAsGetSizeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("size")]
            public string? Size { get; set; }
#nullable restore
#else
            [QueryParameter("size")]
            public string Size { get; set; }
#endif
            /// <summary>The size of the avatar image. If not provided the default size is returned.</summary>
            [QueryParameter("size")]
            public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.GetSizeQueryParameterType? SizeAsGetSizeQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithEntityItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Universal_avatar.View.TypeNamespace.Item.Owner.Item.WithEntityItemRequestBuilder.WithEntityItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
