// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Jira.RestClient.Models;
using Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.Failed;
using Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.Refresh;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\3\webhook
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebhookRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The failed property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.Failed.FailedRequestBuilder Failed
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.Failed.FailedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.WebhookRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhookRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/webhook{?maxResults*,startAt*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.WebhookRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhookRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/webhook{?maxResults*,startAt*}", rawUrl)
        {
        }
        /// <summary>
        /// Removes webhooks by ID. Only webhooks registered by the calling app are removed. If webhooks created by other apps are specified, they are ignored.**[Permissions](#permissions) required:** Only [Connect](https://developer.atlassian.com/cloud/jira/platform/#connect-apps) and [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps) apps can use this operation.
        /// </summary>
        /// <param name="body">Container for a list of webhook IDs.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection">When receiving a 400 status code</exception>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(global::Kubis1982.Atlassian.Jira.RestClient.Models.ContainerForWebhookIDs body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(global::Kubis1982.Atlassian.Jira.RestClient.Models.ContainerForWebhookIDs body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection.CreateFromDiscriminatorValue },
                { "403", global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a [paginated](#pagination) list of the webhooks registered by the calling app.**[Permissions](#permissions) required:** Only [Connect](https://developer.atlassian.com/cloud/jira/platform/#connect-apps) and [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps) apps can use this operation.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.PageBeanWebhook"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection">When receiving a 400 status code</exception>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kubis1982.Atlassian.Jira.RestClient.Models.PageBeanWebhook?> GetAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.WebhookRequestBuilder.WebhookRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kubis1982.Atlassian.Jira.RestClient.Models.PageBeanWebhook> GetAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.WebhookRequestBuilder.WebhookRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection.CreateFromDiscriminatorValue },
                { "403", global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Kubis1982.Atlassian.Jira.RestClient.Models.PageBeanWebhook>(requestInfo, global::Kubis1982.Atlassian.Jira.RestClient.Models.PageBeanWebhook.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Registers webhooks.**NOTE:** for non-public OAuth apps, webhooks are delivered only if there is a match between the app owner and the user who registered a dynamic webhook.**[Permissions](#permissions) required:** Only [Connect](https://developer.atlassian.com/cloud/jira/platform/#connect-apps) and [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps) apps can use this operation.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.ContainerForRegisteredWebhooks"/></returns>
        /// <param name="body">Details of webhooks to register.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection">When receiving a 400 status code</exception>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kubis1982.Atlassian.Jira.RestClient.Models.ContainerForRegisteredWebhooks?> PostAsync(global::Kubis1982.Atlassian.Jira.RestClient.Models.WebhookRegistrationDetails body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kubis1982.Atlassian.Jira.RestClient.Models.ContainerForRegisteredWebhooks> PostAsync(global::Kubis1982.Atlassian.Jira.RestClient.Models.WebhookRegistrationDetails body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection.CreateFromDiscriminatorValue },
                { "403", global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Kubis1982.Atlassian.Jira.RestClient.Models.ContainerForRegisteredWebhooks>(requestInfo, global::Kubis1982.Atlassian.Jira.RestClient.Models.ContainerForRegisteredWebhooks.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Removes webhooks by ID. Only webhooks registered by the calling app are removed. If webhooks created by other apps are specified, they are ignored.**[Permissions](#permissions) required:** Only [Connect](https://developer.atlassian.com/cloud/jira/platform/#connect-apps) and [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps) apps can use this operation.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Container for a list of webhook IDs.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::Kubis1982.Atlassian.Jira.RestClient.Models.ContainerForWebhookIDs body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::Kubis1982.Atlassian.Jira.RestClient.Models.ContainerForWebhookIDs body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a [paginated](#pagination) list of the webhooks registered by the calling app.**[Permissions](#permissions) required:** Only [Connect](https://developer.atlassian.com/cloud/jira/platform/#connect-apps) and [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps) apps can use this operation.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.WebhookRequestBuilder.WebhookRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.WebhookRequestBuilder.WebhookRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Registers webhooks.**NOTE:** for non-public OAuth apps, webhooks are delivered only if there is a match between the app owner and the user who registered a dynamic webhook.**[Permissions](#permissions) required:** Only [Connect](https://developer.atlassian.com/cloud/jira/platform/#connect-apps) and [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps) apps can use this operation.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Details of webhooks to register.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Kubis1982.Atlassian.Jira.RestClient.Models.WebhookRegistrationDetails body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Kubis1982.Atlassian.Jira.RestClient.Models.WebhookRegistrationDetails body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.WebhookRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.WebhookRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.WebhookRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WebhookRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Returns a [paginated](#pagination) list of the webhooks registered by the calling app.**[Permissions](#permissions) required:** Only [Connect](https://developer.atlassian.com/cloud/jira/platform/#connect-apps) and [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps) apps can use this operation.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WebhookRequestBuilderGetQueryParameters 
        {
            /// <summary>The maximum number of items to return per page.</summary>
            [QueryParameter("maxResults")]
            public int? MaxResults { get; set; }
            /// <summary>The index of the first item to return in a page of results (page offset).</summary>
            [QueryParameter("startAt")]
            public long? StartAt { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WebhookRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Webhook.WebhookRequestBuilder.WebhookRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WebhookRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
