// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Jira.RestClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\3\jql\parse
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ParseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse.ParseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ParseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/jql/parse?validation={validation}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse.ParseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ParseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/jql/parse?validation={validation}", rawUrl)
        {
        }
        /// <summary>
        /// Parses and validates JQL queries.Validation is performed in context of the current user.This operation can be accessed anonymously.**[Permissions](#permissions) required:** None.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.ParsedJqlQueries"/></returns>
        /// <param name="body">A list of JQL queries to parse.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kubis1982.Atlassian.Jira.RestClient.Models.ParsedJqlQueries?> PostAsync(global::Kubis1982.Atlassian.Jira.RestClient.Models.JqlQueriesToParse body, Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse.ParseRequestBuilder.ParseRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kubis1982.Atlassian.Jira.RestClient.Models.ParsedJqlQueries> PostAsync(global::Kubis1982.Atlassian.Jira.RestClient.Models.JqlQueriesToParse body, Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse.ParseRequestBuilder.ParseRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Kubis1982.Atlassian.Jira.RestClient.Models.ErrorCollection.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Kubis1982.Atlassian.Jira.RestClient.Models.ParsedJqlQueries>(requestInfo, global::Kubis1982.Atlassian.Jira.RestClient.Models.ParsedJqlQueries.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Parses and validates JQL queries.Validation is performed in context of the current user.This operation can be accessed anonymously.**[Permissions](#permissions) required:** None.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">A list of JQL queries to parse.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Kubis1982.Atlassian.Jira.RestClient.Models.JqlQueriesToParse body, Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse.ParseRequestBuilder.ParseRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Kubis1982.Atlassian.Jira.RestClient.Models.JqlQueriesToParse body, Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse.ParseRequestBuilder.ParseRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse.ParseRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse.ParseRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse.ParseRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Parses and validates JQL queries.Validation is performed in context of the current user.This operation can be accessed anonymously.**[Permissions](#permissions) required:** None.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ParseRequestBuilderPostQueryParameters 
        {
            /// <summary>How to validate the JQL query and treat the validation results. Validation options include: *  `strict` Returns all errors. If validation fails, the query structure is not returned. *  `warn` Returns all errors. If validation fails but the JQL query is correctly formed, the query structure is returned. *  `none` No validation is performed. If JQL query is correctly formed, the query structure is returned.</summary>
            [Obsolete("This property is deprecated, use ValidationAsPostValidationQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("validation")]
            public string? Validation { get; set; }
#nullable restore
#else
            [QueryParameter("validation")]
            public string Validation { get; set; }
#endif
            /// <summary>How to validate the JQL query and treat the validation results. Validation options include: *  `strict` Returns all errors. If validation fails, the query structure is not returned. *  `warn` Returns all errors. If validation fails but the JQL query is correctly formed, the query structure is returned. *  `none` No validation is performed. If JQL query is correctly formed, the query structure is returned.</summary>
            [QueryParameter("validation")]
            public global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse.PostValidationQueryParameterType? ValidationAsPostValidationQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ParseRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.Rest.Api.Three.Jql.Parse.ParseRequestBuilder.ParseRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
