// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Jira.RestClient.V2.Models;
using Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.Default;
using Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.Member;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\2\issuesecurityschemes\level
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LevelRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The default property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.Default.DefaultRequestBuilder Default
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.Default.DefaultRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The member property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.Member.MemberRequestBuilder Member
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.Member.MemberRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.LevelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LevelRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/2/issuesecurityschemes/level{?id*,maxResults*,onlyDefault*,schemeId*,startAt*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.LevelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LevelRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/2/issuesecurityschemes/level{?id*,maxResults*,onlyDefault*,schemeId*,startAt*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a [paginated](#pagination) list of issue security levels.Only issue security levels in the context of classic projects are returned.Filtering using IDs is inclusive: if you specify both security scheme IDs and level IDs, the result will include both specified issue security levels and all issue security levels from the specified schemes.**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.PageBeanSecurityLevel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection">When receiving a 400 status code</exception>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection">When receiving a 401 status code</exception>
        /// <exception cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.PageBeanSecurityLevel?> GetAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.LevelRequestBuilder.LevelRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.PageBeanSecurityLevel> GetAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.LevelRequestBuilder.LevelRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection.CreateFromDiscriminatorValue },
                { "401", global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection.CreateFromDiscriminatorValue },
                { "403", global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.ErrorCollection.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.PageBeanSecurityLevel>(requestInfo, global::Kubis1982.Atlassian.Jira.RestClient.V2.Models.PageBeanSecurityLevel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a [paginated](#pagination) list of issue security levels.Only issue security levels in the context of classic projects are returned.Filtering using IDs is inclusive: if you specify both security scheme IDs and level IDs, the result will include both specified issue security levels and all issue security levels from the specified schemes.**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.LevelRequestBuilder.LevelRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.LevelRequestBuilder.LevelRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.LevelRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.LevelRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.LevelRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a [paginated](#pagination) list of issue security levels.Only issue security levels in the context of classic projects are returned.Filtering using IDs is inclusive: if you specify both security scheme IDs and level IDs, the result will include both specified issue security levels and all issue security levels from the specified schemes.**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LevelRequestBuilderGetQueryParameters 
        {
            /// <summary>The list of issue security scheme level IDs. To include multiple issue security levels, separate IDs with an ampersand: `id=10000&amp;id=10001`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("id")]
            public string[]? Id { get; set; }
#nullable restore
#else
            [QueryParameter("id")]
            public string[] Id { get; set; }
#endif
            /// <summary>The maximum number of items to return per page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("maxResults")]
            public string? MaxResults { get; set; }
#nullable restore
#else
            [QueryParameter("maxResults")]
            public string MaxResults { get; set; }
#endif
            /// <summary>When set to true, returns multiple default levels for each security scheme containing a default. If you provide scheme and level IDs not associated with the default, returns an empty page. The default value is false.</summary>
            [QueryParameter("onlyDefault")]
            public bool? OnlyDefault { get; set; }
            /// <summary>The list of issue security scheme IDs. To include multiple issue security schemes, separate IDs with an ampersand: `schemeId=10000&amp;schemeId=10001`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("schemeId")]
            public string[]? SchemeId { get; set; }
#nullable restore
#else
            [QueryParameter("schemeId")]
            public string[] SchemeId { get; set; }
#endif
            /// <summary>The index of the first item to return in a page of results (page offset).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("startAt")]
            public string? StartAt { get; set; }
#nullable restore
#else
            [QueryParameter("startAt")]
            public string StartAt { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LevelRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.Api.Two.Issuesecurityschemes.Level.LevelRequestBuilder.LevelRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
