// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Jira.RestClient.V2.Rest.AtlassianConnect.One.Migration.Workflow.Rule.Search;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.V2.Rest.AtlassianConnect.One.Migration.Workflow.Rule
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\atlassian-connect\1\migration\workflow\rule
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RuleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The search property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.AtlassianConnect.One.Migration.Workflow.Rule.Search.SearchRequestBuilder Search
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.AtlassianConnect.One.Migration.Workflow.Rule.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.AtlassianConnect.One.Migration.Workflow.Rule.RuleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RuleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/atlassian-connect/1/migration/workflow/rule", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.V2.Rest.AtlassianConnect.One.Migration.Workflow.Rule.RuleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RuleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/atlassian-connect/1/migration/workflow/rule", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
