// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Field;
using Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Item;
using Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Properties;
using Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Workflow;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration
{
    /// <summary>
    /// Builds and executes requests for operations under \rest\atlassian-connect\1\migration
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MigrationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The field property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Field.FieldRequestBuilder Field
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Field.FieldRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The properties property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Properties.PropertiesRequestBuilder Properties
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Properties.PropertiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workflow property</summary>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Workflow.WorkflowRequestBuilder Workflow
        {
            get => new global::Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Workflow.WorkflowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Kubis1982.Atlassian.Jira.RestClient.rest.atlassianConnect.One.migration.item collection</summary>
        /// <param name="position">The key of the Connect app that contains the Jira issue field being migrated.</param>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Item.WithConnectKeyItemRequestBuilder"/></returns>
        public global::Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Item.WithConnectKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("connectKey", position);
                return new global::Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.Item.WithConnectKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.MigrationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MigrationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/atlassian-connect/1/migration", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Jira.RestClient.Rest.AtlassianConnect.One.Migration.MigrationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MigrationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/atlassian-connect/1/migration", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
