// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Confluense.RestClient.App.Properties.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kubis1982.Atlassian.Confluense.RestClient.App.Properties
{
    /// <summary>
    /// Builds and executes requests for operations under \app\properties
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PropertiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Kubis1982.Atlassian.Confluense.RestClient.app.properties.item collection</summary>
        /// <param name="position">The key of the property</param>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.Item.WithPropertyKeyItemRequestBuilder"/></returns>
        public global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.Item.WithPropertyKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("propertyKey", position);
                return new global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.Item.WithPropertyKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/app/properties{?cursor*,limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/app/properties{?cursor*,limit*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets Forge app properties. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesGetResponse?> GetAsPropertiesGetResponseAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder.PropertiesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesGetResponse> GetAsPropertiesGetResponseAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder.PropertiesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesGetResponse>(requestInfo, global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets Forge app properties. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsPropertiesGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesResponse?> GetAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder.PropertiesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesResponse> GetAsync(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder.PropertiesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesResponse>(requestInfo, global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets Forge app properties. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder.PropertiesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder.PropertiesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets Forge app properties. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PropertiesRequestBuilderGetQueryParameters 
        {
            /// <summary>Used for pagination, this opaque cursor represents the last returned property key. It will be included in the response body as the next link. Use this key to request the next set of results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>Maximum number of app properties per result to return. If more results exist, use the last returned property key from the Link field in the response body as a cursor to retrieve the next set of results.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PropertiesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Kubis1982.Atlassian.Confluense.RestClient.App.Properties.PropertiesRequestBuilder.PropertiesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
