// <auto-generated/>
#pragma warning disable CS0618
using Kubis1982.Atlassian.Confluense.RestClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BlogpostPutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The body property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody.BlogpostPutRequestBody_body? Body { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody.BlogpostPutRequestBody_body Body { get; set; }
#endif
        /// <summary>Created date of the blog post in the format of &quot;yyyy-MM-ddTHH:mm:ss.SSSZ&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Id of the blog post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>ID of the containing space.This currently **does not support moving the blog post to a different space**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpaceId { get; set; }
#nullable restore
#else
        public string SpaceId { get; set; }
#endif
        /// <summary>The updated status of the blog post.Note, if you change the status of a blog post from &apos;current&apos; to &apos;draft&apos; and it has an existing draft, the existing draft will be deleted in favor of the updated draft.Additionally, this endpoint can be used to restore a &apos;trashed&apos; or &apos;deleted&apos; blog post to &apos;current&apos; status. For restoration, blog post contents will not be updated and only the blog post status will be changed.</summary>
        public global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody_status? Status { get; set; }
        /// <summary>Title of the blog post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody_version? Version { get; set; }
#nullable restore
#else
        public global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody_version Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody"/> and sets the default values.
        /// </summary>
        public BlogpostPutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "body", n => { Body = n.GetObjectValue<global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody.BlogpostPutRequestBody_body>(global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody.BlogpostPutRequestBody_body.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "spaceId", n => { SpaceId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody_status>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "version", n => { Version = n.GetObjectValue<global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody_version>(global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody_version.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody.BlogpostPutRequestBody_body>("body", Body);
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("spaceId", SpaceId);
            writer.WriteEnumValue<global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody_status>("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteObjectValue<global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody_version>("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostBodyWrite"/>, <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostNestedBodyWrite"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BlogpostPutRequestBody_body : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostBodyWrite"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostBodyWrite? BlogPostBodyWrite { get; set; }
#nullable restore
#else
            public global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostBodyWrite BlogPostBodyWrite { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostNestedBodyWrite"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostNestedBodyWrite? BlogPostNestedBodyWrite { get; set; }
#nullable restore
#else
            public global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostNestedBodyWrite BlogPostNestedBodyWrite { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody.BlogpostPutRequestBody_body"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody.BlogpostPutRequestBody_body CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item.BlogpostPutRequestBody.BlogpostPutRequestBody_body();
                if("BlogPostBodyWrite".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.BlogPostBodyWrite = new global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostBodyWrite();
                }
                else if("BlogPostNestedBodyWrite".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.BlogPostNestedBodyWrite = new global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostNestedBodyWrite();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BlogPostBodyWrite != null)
                {
                    return BlogPostBodyWrite.GetFieldDeserializers();
                }
                else if(BlogPostNestedBodyWrite != null)
                {
                    return BlogPostNestedBodyWrite.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(BlogPostBodyWrite != null)
                {
                    writer.WriteObjectValue<global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostBodyWrite>(null, BlogPostBodyWrite);
                }
                else if(BlogPostNestedBodyWrite != null)
                {
                    writer.WriteObjectValue<global::Kubis1982.Atlassian.Confluense.RestClient.Models.BlogPostNestedBodyWrite>(null, BlogPostNestedBodyWrite);
                }
            }
        }
    }
}
#pragma warning restore CS0618
