// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Confluense.RestClient.Blogposts.Item
{
    /// <summary>The updated status of the blog post.Note, if you change the status of a blog post from &apos;current&apos; to &apos;draft&apos; and it has an existing draft, the existing draft will be deleted in favor of the updated draft.Additionally, this endpoint can be used to restore a &apos;trashed&apos; or &apos;deleted&apos; blog post to &apos;current&apos; status. For restoration, blog post contents will not be updated and only the blog post status will be changed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BlogpostPutRequestBody_status
    {
        [EnumMember(Value = "current")]
        #pragma warning disable CS1591
        Current,
        #pragma warning restore CS1591
        [EnumMember(Value = "draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
    }
}
