// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kubis1982.Atlassian.Confluense.RestClient.SpaceRoleMode
{
    /// <summary>The space role mode.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SpaceRoleModeGetResponse_mode
    {
        [EnumMember(Value = "PRE_ROLES")]
        #pragma warning disable CS1591
        PRE_ROLES,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROLES_TRANSITION")]
        #pragma warning disable CS1591
        ROLES_TRANSITION,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROLES")]
        #pragma warning disable CS1591
        ROLES,
        #pragma warning restore CS1591
    }
}
